### ISSUE TITLE
Method for managing created urls?

### ISSUE THREAD

**Issue by badbox29** [diffra/Lard#1]
Hi, I am unable to find how to manage the URLs you've created.  Can you advise?

Thank you!

**Comment by jbertelson** [comment]
None currently, but the database was designed with this in mind as it includes view count and last visited data. actual management UI coming soon! In the meantime you can use sqlite3 to open the database and view statistics there.

**Comment by fivestones** [comment]
Would like to see this too! :-)

**Comment by jbertelson** [comment]
Added a basic admin ui at /admin -- make sure to add a user/password to your config.ini or you won't be able to log into it.
